// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Health")));
bytes32 constant HealthTableId = _tableId;

struct HealthData {
  uint256 current;
  uint256 maxHealth;
}

library Health {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT256;
    _schema[1] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "current";
    _fieldNames[1] = "maxHealth";
    return ("Health", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get current */
  function getCurrent(address owner, bytes32 world) internal view returns (uint256 current) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get current (using the specified store) */
  function getCurrent(IStore _store, address owner, bytes32 world) internal view returns (uint256 current) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set current */
  function setCurrent(address owner, bytes32 world, uint256 current) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((current)));
  }

  /** Set current (using the specified store) */
  function setCurrent(IStore _store, address owner, bytes32 world, uint256 current) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((current)));
  }

  /** Get maxHealth */
  function getMaxHealth(address owner, bytes32 world) internal view returns (uint256 maxHealth) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get maxHealth (using the specified store) */
  function getMaxHealth(IStore _store, address owner, bytes32 world) internal view returns (uint256 maxHealth) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set maxHealth */
  function setMaxHealth(address owner, bytes32 world, uint256 maxHealth) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((maxHealth)));
  }

  /** Set maxHealth (using the specified store) */
  function setMaxHealth(IStore _store, address owner, bytes32 world, uint256 maxHealth) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((maxHealth)));
  }

  /** Get the full data */
  function get(address owner, bytes32 world) internal view returns (HealthData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, address owner, bytes32 world) internal view returns (HealthData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(address owner, bytes32 world, uint256 current, uint256 maxHealth) internal {
    bytes memory _data = encode(current, maxHealth);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, address owner, bytes32 world, uint256 current, uint256 maxHealth) internal {
    bytes memory _data = encode(current, maxHealth);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(address owner, bytes32 world, HealthData memory _table) internal {
    set(owner, world, _table.current, _table.maxHealth);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, address owner, bytes32 world, HealthData memory _table) internal {
    set(_store, owner, world, _table.current, _table.maxHealth);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (HealthData memory _table) {
    _table.current = (uint256(Bytes.slice32(_blob, 0)));

    _table.maxHealth = (uint256(Bytes.slice32(_blob, 32)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(uint256 current, uint256 maxHealth) internal view returns (bytes memory) {
    return abi.encodePacked(current, maxHealth);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(address owner, bytes32 world) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;
  }

  /* Delete all data for given keys */
  function deleteRecord(address owner, bytes32 world) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, address owner, bytes32 world) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(owner)));
    _keyTuple[1] = world;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
