// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ToDo, ToDoData, ToDoTableId } from "./tables/ToDo.sol";
import { Stories, StoriesData, StoriesTableId } from "./tables/Stories.sol";
import { StoryArt, StoryArtData, StoryArtTableId } from "./tables/StoryArt.sol";
import { Narratives, NarrativesData, NarrativesTableId } from "./tables/Narratives.sol";
import { Wallet, WalletTableId } from "./tables/Wallet.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { Health, HealthData, HealthTableId } from "./tables/Health.sol";
import { Xp, XpTableId } from "./tables/Xp.sol";
import { Strength, StrengthTableId } from "./tables/Strength.sol";
import { Dexterity, DexterityTableId } from "./tables/Dexterity.sol";
import { Constitution, ConstitutionTableId } from "./tables/Constitution.sol";
import { Intelligence, IntelligenceTableId } from "./tables/Intelligence.sol";
import { Wisdom, WisdomTableId } from "./tables/Wisdom.sol";
import { Charisma, CharismaTableId } from "./tables/Charisma.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
