// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface INarrativesSystem {
  function createNarrative(
    bytes32 world,
    int256 order,
    string memory from,
    string memory text
  ) external returns (bytes32);

  function editNarrative(
    bytes32 id,
    bytes32 world,
    int256 order,
    string memory from,
    string memory text
  ) external returns (bool);

  function removeNarrative(bytes32 id) external returns (bool);
}
